module.exports={
    login:require("./libs.login"),
    createUser:require("./libs.createUser"),
    findUser:require("./libs.findUser"),
    deleteUser:require("./libs.deleteUser"),
    checkSession:require("./libs.checkSession"),
    signIn:require("./libs.signIn"),
    signOut:require("./libs.signOut"),
    listOfUsers:require("./libs.listOfUsers")
}
